### ISSUE TITLE
Many posts and comments in the data.csv are removed. Can you upload more MHP data?

### ISSUE THREAD

**Issue by lsy641** [MichiganNLP/MHP-and-Peers-Reddit#1]
Dear Charles and Allison,

Thanks for your massive contribution to mental health resources for NLPers!
As many reddits have been deleted, I only got 7971 post-comment pairs with MHP self-identification after data cleaning. May I know if is there any way to get more data?

Sincerely,
Siyang Liu

First-year phd,
LIT group,
University of Michigan

**Comment by alahnala** [comment]
Hi Siyang Liu! I'm sorry I didn't see the notification earlier! Can you write me an email to alcllahn@umich.edu to request the dataset?

**Comment by lsy641** [comment]
Hi, I just sent you an email. Did you receive it?

**Comment by alahnala** [comment]
Hi Siyang! Yes, and I have just sent you a response. Feel free to reach out if there's anything else I can help with :)
